# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job1: 
    name: Print repository name
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.repository.name }}"
  Job2:
    name: Create dispatch event
    needs: [Job1]
    strategy:
      matrix:
        repo: ['Gau02/main']
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: my-event
